### ISSUE TITLE
Pulumi Audit Logs API (JSON) should validate that either continuationToken or startTime is set but not both

### ISSUE THREAD

**Issue by alexstojda** [pulumi/console-requests#133]
### What happened?

According to the docs, a `continuationToken` is included in the response body to use for retrieving the next set of results, if results were truncated. 

However, when including this token in the following request to retrieve the next set of results, the token does not change and the results returned are the same as the initial request which did not contain the token. 

Screenshots (org name has been omitted): 

First request without continuationToken: 
<img width="668" alt="image" src="https://user-images.githubusercontent.com/1353716/200702512-28b99bb2-73e6-4d5c-8b88-3ed21f8ea489.png">

Second request with continuationToken:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/1353716/200702837-948fb8c2-b2da-43ba-b17f-71d092081705.png">

Notice that the timestamp of the first result, and the continuationToken do not change in the second request. 

### Steps to reproduce

1. Make a valid request to `https://api.pulumi.com/api/orgs/{org}/auditlogs` with an arbitrary start time
2. Make a second request including the `continuationToken` of the first request. Notice the results are unchanged. 

### Expected Behavior

Results should start from the continuatioToken

### Actual Behavior

Results start from the startTime and not the contiunationToken

### Additional context

Unrelated suggestion: Rename the `continuationToken` to something like `continueFrom` since the token is clearly the timestamp of the last result :) 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EvanBoyle** [comment]
My guess is that the bug here is that you have more than 100 (the max number of results) audit log events recorded for the same continuation token and you get stuck in a loop receiving the same continuation token. If you decrement the continuation token by 1, do you get a new page of results?

**Comment by alexstojda** [comment]
@EvanBoyle Decrementing the token did not change anything. 

However, I had the impulse to try removing the `startTime` query param and only include `continuationToken` and was able to get a new page of results!

This begs the question of course, why even bother with the `continuationToken` query param, when passing the token to the `startTime` param yields the same result :P

**Comment by EvanBoyle** [comment]
I think `continuationToken` and `startTime` are supposed to be mutually exclusive and we should throw a validation error if you provide both. Sorry for the confusion here!
