### ISSUE TITLE
I'd like to have the possibility to delete a stack on the website

### ISSUE THREAD

**Issue by janban-outlook** [pulumi/console-requests#216]
Currently, when you want to delete a stack, you need to execute a few command from your local machine. That's sometimes annoying.
I prefer to have a deletion option online.

**Comment by meagancojocar** [comment]
Hi @janvanveldhuizen, thank you for the feature request!! Is your use case to delete an empty stack from the Pulumi Cloud console or one with resources? 

Today you can delete a stack from the console if you have no resources in it. If you have resources and are using Pulumi Deployments you can Click to Destroy from the console. But it sounds like what you are looking for is to destroy and delete a stack that has resources in it from the console?

**Comment by janban-outlook** [comment]
Imagine that you have been experimenting with Pulumi, testing out various features, and subsequently deleted your local project. Since you were working with an existing Azure infrastructure, you prefer not to use the destroy feature. In situations like this, it would be convenient to have the ability to delete the project directly from the Pulumi website, without needing to recreate the YAML files on your local system.

**Comment by EvanBoyle** [comment]
@janvanveldhuizen you do not need the project YAML file to delete a stack with the CLI. You can use the `--stack` flag to specify the stack, and the `--force` flag to bypass having to run a destroy if there are still resources in the stack. For example:

```console
$ pulumi stack rm --stack org/project/stack --force
```

**Comment by janban-outlook** [comment]
That's what I need. Thanks!
