### ISSUE TITLE
Can't add additional licenses on website

### ISSUE THREAD

**Issue by ajheunis** [pulumi/console-requests#218]
On the Modify Subscription dialog, I'm unable to add additional licenses.

![Screenshot 2023-04-13 114612](https://user-images.githubusercontent.com/1893011/231814588-6e9cc497-b901-440b-b071-3c9097543321.png)

**Comment by meagancojocar** [comment]
@ajheunis we're looking into this and will let you know when its fixed! Thank you for reporting it.

**Comment by isabeldepapel** [comment]
@ajheunis We just released a fix for this. If you're still having issues, please let us know
