### ISSUE TITLE
Pulumi Deployments: Dependency Caching 

### ISSUE THREAD

**Issue by hendrysadrak** [pulumi/console-requests#220]
Build and deployment times can increase significantly as projects grow due to the lack of dependency caching. 

Adding dependency caching functionality to Pulumi Deployments would be a valuable enhancement, improving efficiency and performance. 

IMO A good example to look at for inspiration is GitHub Actions.  https://github.com/actions/cache

**Feature Request:**

* Add dependency caching functionality for Pulumi Deployments
* Allow users to configure and customize cache storage and cache invalidation strategies
* Support caching for popular programming languages and platforms

**Comment by EvanBoyle** [comment]
Thanks for opening the issue. I agree this would be great to add to deployments.

I'm curious, are you currently having performance problems?

**Comment by hendrysadrak** [comment]
Currently, the biggest chunk of time is spent downloading the npm packages. It would be great if the dependencies could be cached.

**Comment by deni64k** [comment]
Caching `GOCACHE` and `GOMODCACHE` would significantly help to speed up compilation.

**Comment by cleverguy25** [comment]
https://www.pulumi.com/blog/announcing-dependency-caching-deployments/
