### ISSUE TITLE
Wrong link for Azure in the project / stack creation process

### ISSUE THREAD

**Issue by TechWatching** [pulumi/console-requests#224]
When creating an azure project/stack in the pulumi (service) dahsboard, the link to "Ensure the Pulumi Azure provider is set up" points to the classic azure provider instead of the azure-native one (even if the setup is the same, I think it should point the azure native provider)

## Expected behavior

The link "Ensure the Puumi Azure provider is set up" should points to this : https://www.pulumi.com/registry/packages/azure-native/installation-configuration/#authentication-methods 

## Current behavior
The link "Ensure the Puumi Azure provider is set up" currently points to this : https://www.pulumi.com/registry/packages/azure/installation-configuration/#authentication-methods

## Steps to reproduce

1. Go to app.pulumi.com
2. Create a new Azure project / stack

## Context (Environment)
As I am familiar with Pulumi and Azure Native it does not affect me much but it would affect new Pulumi users that don't know the differences between Classic Azure and Azure native provider. It could mislead them to the wrong documentation when they will be looking for the Azure provider doc.

## Affected feature

Project/stack creation

**Comment by mnlumi** [comment]
Thank you for creating this issue! I've gone ahead and opened a PR to update the link to point to Azure Native.
