### ISSUE TITLE
wrong sign/arrow direction in Pulumi console

### ISSUE THREAD

**Issue by alexandrelussier** [pulumi/console-requests#226]
The arrow of total resource is pointing up 
![image](https://user-images.githubusercontent.com/32465975/234881539-8d0bb964-83d6-4085-be70-7326b045daaf.png)

## Expected behavior
it should point down, since the graph shows that the resources count is going down

## Steps to reproduce

1.
2.
3.
4.

**Comment by EvanBoyle** [comment]
Would be good for us to figure out if there is a mismatch between the time window in the total resources widget and the resources graph.

**Comment by alexandrelussier** [comment]
> Would be good for us to figure out if there is a mismatch between the time window in the total resources widget and the resources graph.

my org is akinox if this can help you drill down the resource count
