### ISSUE TITLE
Allow org tokens to publish Policy Packs

### ISSUE THREAD

**Issue by raildo** [pulumi/console-requests#229]
We're trying to build a CI process to publish new policy packs on a git repo, on our current CI we're using an organization token for Pulumi which works basically as a member role. However, nowadays, we need admin's permission to publish policy packs, which is only possible via personal tokens.

I would like to be able to publish policy packs either using the organizational token as we do for other commons tasks.

**Comment by EvanBoyle** [comment]
Fixed via https://github.com/pulumi/pulumi-cloud-requests/issues/242
