### ISSUE TITLE
Continuous Deliver Links do not resolve (404)

### ISSUE THREAD

**Issue by DavidJFelix** [pulumi/console-requests#235]
In the `settings/integrations` page, many of the links for continuous delivery providers do not resolve to the correct documentation and 404 instead, Including github actions. It looks like the urls are outdated:

Tries to go to: `https://www.pulumi.com/docs/docs/using-pulumi/continuous-delivery/cd-github-actions/`
but should instead go to: `https://www.pulumi.com/docs/using-pulumi/continuous-delivery/github-actions/`

Image of the links:
<img width="855" alt="image" src="https://github.com/pulumi/pulumi-cloud-requests/assets/263432/aa06a80c-7281-4e5a-a072-a3b34ff49bf3">

**Comment by meagancojocar** [comment]
Thank you so much for reporting this! We will fix it in the next day or so.

**Comment by susanev** [comment]
hi @DavidJFelix, this has been fixed and should roll out later today or tomorrow. thx again for the report, and sry for the trouble!!
