### ISSUE TITLE
Org Access Tokens - Full Admin

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/console-requests#242]
Org Access Tokens don't currently have a full set of admin features. It would be useful to allow org access tokens to be created with a full set of admin privileges to allow the token to perform _any_ operation, where needed.

Perhaps a nice step towards fine-grain access control onto tokens.

**Comment by caseyyh** [comment]
related: https://github.com/pulumi/pulumi-service/issues/13422

**Comment by djgrove** [comment]
This is now live in prod!
