### ISSUE TITLE
MS Teams webhook support

### ISSUE THREAD

**Issue by chaffees** [pulumi/console-requests#263]
The basic issue we are running into is that Pulumi does not have built-in support for Microsoft Teams as it does for Slack. So, we need to run something that receives the webhook from Pulumi and then passes it to Teams in a way that Teams can consume. This is inefficient and creates unnecessary complexity in our Pulumi environment. We would like to request support for MS Teams webhook support and integration.

## Affected feature
Webhooks.

**Comment by meagancojocar** [comment]
Thanks for opening this issue @chaffees! This is on our roadmap, we will keep this issue updated when we get to it.

**Comment by komalali** [comment]
This is now supported in the product! Please try it out and let us know what you think :D 

https://www.pulumi.com/docs/pulumi-cloud/webhooks/#microsoft-teams-webhooks
