### ISSUE TITLE
Dashboard / Latest stack update refresh / misleading issue

### ISSUE THREAD

**Issue by patilpappmodz1** [pulumi/console-requests#278]
When we switch organization on the Pulumi Cloud console, the latest stack update section doesn't refresh initially. It shows the stacks from a different org. When we refresh the screen, it shows the ones from the correct org.

If this is indeed showing the stack updates from ALL org, then the description show that these udates are from all the orgs for the user.

## General Feedback

![image](https://github.com/pulumi/pulumi-cloud-requests/assets/86608929/b1954e14-aaae-4108-86d3-10a86ded2649)

**Comment by meagancojocar** [comment]
Hi @patilpappmodz1 thank you for this feedback! We are looking into it, we may need more information to debug what is going on here but I will let you know.
