### ISSUE TITLE
Importing Resource Results in Undefined Operation and Resource in Console

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/console-requests#29]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When importing resources into Pulumi, the 'Activity' tab of the import operation shows `undefined` for the operation and resource.

### Steps to reproduce

1. create an empty pulumi project
2. import any resource into the project using `pulumi import ....`
3. check the console, for the stack's activity the import activity.

Expected: Importing a resource should not show `undefined` for resource or operation
Actual: Importing a resource shows `undefined` for resource and operation.

See screenshot:
![image](https://user-images.githubusercontent.com/25461821/144683790-045f00ae-ef41-4aca-9391-57fa27921257.png)

**Comment by chrsmith** [comment]
This has been fixed and will be deployed soon. 🎉
