### ISSUE TITLE
I am not really all that impressed so far.

### ISSUE THREAD

**Issue by cbitterfield** [pulumi/console-requests#290]
## General Feedback
1. I had no end of issues with pulumi_aws or pulumi_awsx. Sometimes pulumi_docker had DockerBuild and sometimes it didn't.
2. I want nothing to do with "native aws" if that is going to be some weird nodeJS thing. Just want to work in Python.

I tried for two days to create a very simple AWS ECS service with two services. None of the examples are really all that clear and pulumi TV wasn't much help either. It's great to spin up 1 NGINX instance but not really a very good demonstration. Also, no one will really just run an image from Docker pull without some modification.

The task was create an ECS service running nginx as a webserver and php-fpm as a second service. I need to create them with Docker files in ECR. Nothing the AI produced worked. It frequently had major typos and failed to close () or """ quotes. I am not sure where you are going with _aws _awsx or "native" mode. The AI is useless. Seemed promising but in the end useless. I spent way to much time figure out little details. I didn't need 335 unworkable examples in multiple languages. There are only 25 aws python examples.

It really should not be this hard to get a working example of a basic PHP webserver on Nginx. I really don't understand and I could not find an answer to what "native mode" offers except for more complexity.

**Comment by phillipedwards** [comment]
Hello- sorry you're having a _less_ than ideal experience with Pulumi so far. Let me see if I can provide some help and clear things up.

- This repo tracks requests/issues for Pulumi's SAAS application (https://app.pulumi.com). For items about Pulumi SDKs or AWS providers specifically, github.com/pulumi/pulumi and/or github.com/pulumi/pulumi-aws are better locations. 
- Pulumi has a vibrant community slack where people (including Pulumi employees) are more than happy to look at code to help diagnose issues and ultimately get people unblocked. https://slack.pulumi.com/ I think if you posted the problems you're running into and included a bit of code, lots of people would volunteer to assist.
- Pulumi AI is by no means perfect but can be a great tool in helping someone get up and running. We would definitely appreciate the feedback on https://pulumi.com/ai if possible.
- In Pulumi terms `native` designates a provide which is Pulumi owned, maintained, and built from a cloud providers' API. AWS Native and Azure Native are two examples of these types of providers. Note, AWS Native is in preview and my recommendation is to use AWS Classic for now.
- Quoting you, _It really should not be this hard to get a working example of a basic PHP webserver on Nginx._ I agree and would love to help out. I'm happy to assist in community slack if you'd like to join and DM me (@Phillip Edwards) to get going on some troubleshooting.

**Comment by EvanBoyle** [comment]
Thanks for the feedback @cbitterfield, please do reach out on community slack and we can get you some assistance!
