### ISSUE TITLE
pulumi always shows "uncommitted changes were present at the time of this update" warning

### ISSUE THREAD

**Issue by yehudamakarov** [pulumi/console-requests#294]
I have a stack that **always** shows "uncommitted changes were present at the time of this update" in the UI. Even if I `update` or `refresh` after pushing the most recent commits to the repository.

## Expected behavior

The warning should only show when applicable.

## Current behavior
The warning always shows no matter what I do. I have another stack where it behaves normally.

## Steps to reproduce

1. make a typescript pulumi project
2. make sure the repo is connected via integrations
3. place the `pulumi.yaml` **not at the root of the project** (mine is `/iac/pulumi.yaml`) 
5. make sure all commits are pushed
6. `pulumi up` and the warning is still there

**Comment by EvanBoyle** [comment]
@yehudamakarov would it be possible for you to run `git status` in your CI job after `pulumi up` runs? Would love to rule out that there aren't some unexpected changes in the working directory. Sometimes this can happen if you run `pulumi config set`, or if installing dependencies changes a `yarn.lock` or `go.sum` file for instance.

**Comment by yehudamakarov** [comment]
Yes, but as of now I just run it locally from my own machine.

**Comment by yehudamakarov** [comment]
- @EvanBoyle I found a `DS_Store` with `git status`
- I ran `pulumi up` then verified `git status` returned `clean` 
- The UI does **not** show the warning anymore.

Thanks!
