### ISSUE TITLE
Allow OIDC subject to be configured

### ISSUE THREAD

**Issue by polivbr** [pulumi/console-requests#295]
It is currently not practical to use OIDC with Azure AD for environments with a large number of stacks. Due to Azure AD requiring an exact match on the subject, four separate federated credentials need to be created for each stack, which is not only excessive, but will quickly exceed the Azure AD limits.

It would be extremely helpful to be able to configure the subject in the OIDC token. This would allow the match to be performed at a coarser level of granularity (stack/project/org).

For what it's worth, GitHub has the same issue and their solution is to allow you to customize the subject.

**Comment by pgavlin** [comment]
For reference, here are GH's docs on subject customization: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#customizing-the-subject-claims-for-an-organization-or-repository

This is largely in line with what I've been thinking. It seems unsafe to allow total subject customization, as that opens the doors to badly misconfigured security (e.g. OIDC subjects that are shared between organizations, which is a no-go). But allowing what sort of data ends up in the subject seems reasonable.
