### ISSUE TITLE
Organization without admin users

### ISSUE THREAD

**Issue by egjimenezg** [pulumi/console-requests#311]
Hi, the account of the admin user of our organization was recently deleted and now none of the users are administrators.
Is there a way to assign the admin role to another user even though all users in the organization are members?
How can I contact support to resolve this issue?
It's impossible to access to our organization settings if there aren't admin users.

**Comment by EvanBoyle** [comment]
Please email support@pulumi.com

**Comment by egjimenezg** [comment]
> support@pulumi.com

Thanks! I just sent an email.
