### ISSUE TITLE
Where do I access support?

### ISSUE THREAD

**Issue by buchs** [pulumi/console-requests#317]
## General Feedback

I can't find a way to submit a support ticket.

![image](https://github.com/pulumi/pulumi-cloud-requests/assets/797361/f59de064-09c5-4f70-9b22-f5c49ccbd757)

**Comment by meagancojocar** [comment]
Hi Kevin, 

Thank you for raising this! You can use this link on our main website: https://www.pulumi.com/contact/ or email support@pulumi.com.

Inside the product, admins have a contact support button on the Billing page. For non-admins, it lives in your user dashboard incase you need help with your account. Where the hyperlink says "Need help" in the below image. 
![Screen Shot 2023-10-31 at 11 07 32 AM](https://github.com/pulumi/pulumi-cloud-requests/assets/50200557/6eed2130-8d7e-411d-a911-ae19271c9584)

Let me know if you need anything else!
Meagan

**Comment by buchs** [comment]
Hi Meagan (@meagancojocar ),

I guess that Get Started block does not hang around on the dashboard. This is all I see:
![image](https://github.com/pulumi/pulumi-cloud-requests/assets/797361/dfc93f98-75b5-4b3e-962b-268bef50ff7f)
