### ISSUE TITLE
Pulumi Deployment: Slow provisioning and execution time

### ISSUE THREAD

**Issue by mattfield** [pulumi/console-requests#318]
When executing a preview in Deployments, there's very often a lag time of a good few minutes before the requested operation actually begins. As an example, see the attached screenshot - nearly 4 minutes elapses between "Previewing update" and the preview actually starting. All in all, it takes 5-6 minutes just for a preview to complete. When running the same preview locally (but still executed on Pulumi Cloud) it starts and returns in less than 30s, and it is also much faster than 5-6 minutes when executed via Github Actions.

![image](https://github.com/pulumi/pulumi-cloud-requests/assets/686826/18ad76db-86f0-458f-a641-7b08e03aa12c)

## Expected behavior

Pulumi Deployments operations should execute and return much faster, ideally in an equivalent time to executions triggered from other sources.

## Current behavior

Pulumi Deployments operations have an unexpectedly long latency between an op being requested and it actually executing and returning. This has negative consequences for the viability of the solution, particularly for a large number of stacks.

## Steps to reproduce

Please see attached screenshot above.

## Context (Environment)

This lag time has negative consequences for the viability of the solution, particularly for multiple stacks. This is compounded by only being allowed to run 5 concurrent stack Deployments on the Team Edition.

## Affected feature

Pulumi Deployments

**Comment by cleverguy25** [comment]
I have looked into this over several days.  Partially, this is related to dependencies, but in this case that is not the only factor, it seems to be the raw CPU and network bandwidth allocated to executing this operation vs what the user has running on their local machine.  We will investigate a roadmap item to allocate larger instances.

**Comment by komalali** [comment]
Related to https://github.com/pulumi/pulumi-cloud-requests/issues/220

**Comment by cleverguy25** [comment]
https://www.pulumi.com/blog/announcing-dependency-caching-deployments/
