### ISSUE TITLE
ResourceOptions not in resource display on UI

### ISSUE THREAD

**Issue by oz-chewie** [pulumi/console-requests#321]
Resources in the UI does not show ResourceOptions on a particular resource.
From a Pulumi engineer:

> The information is in the state file so the service UI should be able to show it.

## Steps to reproduce
Go to UI, type in a resource name in the resource search dialog, when you see the resource there is no information for ResourceOptions.

## Context (Environment)
For instance I want to see if retain_on_delete is True or False on a Snowflake table.

**Comment by meagancojocar** [comment]
Hi there! Thank you for this feedback and for opening an issue. I'm guessing the answer is both, but in your use case are you looking to be able to see ResourceOptions for a specific resource or are you wanting to search by resources with that ResourceOption? I'm trying to think through if this would be solved by Resource Search or the Resource details tab on the stack page.

**Comment by oz-chewie** [comment]
Definitely want to look for a specific resource but yeah - having a search
capability would really help too especially for the case that I brought up
where a resource having retain_on_delete=False might end up deleting
something you did not intend for deletion!  Snowflake tables being a really
good case here.

**Comment by komalali** [comment]
`retainOnDelete` is now included on the resource page.
