### ISSUE TITLE
Cloud configuration page incorrectly displaying strings as numbers

### ISSUE THREAD

**Issue by ZacHigi** [pulumi/console-requests#324]
Cloud configuration appears to be detecting and parsing certain strings as numbers.

## Expected behavior

Explicitly marked strings in config should be displayed as such.

## Current behavior
Explicitly marked strings are parsed as numbers .

## Steps to reproduce
1. Take any stack and add a configuration value with a decimal and trailing zero.  (e.g. "10.20")
![image](https://github.com/pulumi/pulumi-cloud-requests/assets/68551134/b4ea86f3-78be-469d-b2ae-310df237a16c)

2. Review the configuration value on Pulumi cloud and note that is parsed as a decimal and inaccurately trims trailing zeros.  (e.g. "10.2")
![image](https://github.com/pulumi/pulumi-cloud-requests/assets/68551134/37b9ca8f-ea9b-42b1-9f41-324a064545b6)

## Context (Environment)
It appears to be a portal display issue only.  The stack and any pulumi up commands accurately treat the value as a string.

**Comment by kimberleyamackenzie** [comment]
Hi @ZacHigi - thank you for reporting this!  We have merged a change that will prevent the inaccurate trimming of trailing zeros.  This will be live with our next release, so please be on the lookout for it and re-open this issue if you feel that there are still concerns with the way the configuration values are rendered.  Thank you again!
