### ISSUE TITLE
[cloud-search] Allow filtering resources per team owning the resources

### ISSUE THREAD

**Issue by aureq** [pulumi/console-requests#326]
The Pulumi Resource Search syntax doesn't allow filtering per Pulumi team names. Because this feature is missing, it's impossible to understand how many resources belong to a given team.

## Affected feature

* pulumi resource search

**Comment by meagancojocar** [comment]
Hi Aurel, we do have this feature. Find more details [in the docs](https://www.pulumi.com/docs/pulumi-cloud/insights/search/#existence-queries), you can filter on a team name with the syntax `team:`.

Let me know if you ran into issues with this.
