### ISSUE TITLE
In console stack view cannot open resource page in new tab

### ISSUE THREAD

**Issue by assafvayner** [pulumi/console-requests#331]
When viewing resources in my project in a specific stack I may want to open the individual resource page in a separate tab, however I cannot do that any way I've tried.

I'm on MacOS on chrome browser. Hitting cmd + click simply opens the page in the same tab. Right clicking a row does not show the option to open in a new tab as seen in screenshot below.

<img width="548" alt="Screenshot 2023-12-06 at 5 32 22 PM" src="https://github.com/pulumi/pulumi-cloud-requests/assets/23582578/2d50dbd1-24d7-48bd-adb3-a206cde18094">

**Comment by kimberleyamackenzie** [comment]
Hi @assafvayner - thank you for reporting this!  A fix has been merged that should enable the open in new tab scenario for you, and will be live with our next release.  Expect to see this come to you within the next few days.
