### ISSUE TITLE
Can not save deployment configuration

### ISSUE THREAD

**Issue by WanchiaTsai** [pulumi/console-requests#336]
I following the document to configure OIDC in the pulumi console.
https://www.pulumi.com/docs/pulumi-cloud/oidc/gcp/#configure-oidc-in-the-pulumi-console

i filled up all the input box, but i can not save the setting. 
The save button is disable.
 
![400727](https://github.com/pulumi/pulumi-cloud-requests/assets/12000887/6fcbc89b-00b4-471b-82eb-d52c9bdc7351)

**Comment by komalali** [comment]
Hi @WanchiaTsai thanks for the report. It would be helpful to have more context on how you are hitting this issue. I am not able to reproduce if all other required fields of the deployment settings are filled correctly. Can you provide specific repro steps or provide a full screenshot of your entire deployment settings?

**Comment by cleverguy25** [comment]
Since we are unable to reproduce this, I am closing this for now.  But happy to reopen if we get specific repro steps.
