### ISSUE TITLE
Pulumi fails to remove a (now unexistant) service principal (as I deleted it manually).

### ISSUE THREAD

**Issue by GeneralSan** [pulumi/console-requests#338]
Hi, I created an application and service principal with Pulumi.
Then realized that they weren't needed.  I cleaned up some stuff in Azure, together with this application and service principal.

Now Pulumi thinks it is still there and wants to delete it, but ends in timeout/error.
Pulumi fails every run now... as the situation cannot be unmade.  
If I could remove it from the Pulumi resources, I could fix it, but I think I have no access to do that...
So the only way to fix this is with a Pulumi update...

**Comment by cleverguy25** [comment]
Have you tried 'pulumi refresh' to update the current state and reflect the manual changes?  If that doesn't work you can also try Pulumi state delete, [docs are here](https://www.pulumi.com/docs/cli/commands/pulumi_state_delete/).

**Comment by GeneralSan** [comment]
pulumi state delete does the trick indeed.  Thx, you resolved my issue.
