### ISSUE TITLE
Proxmox cloud provider on the https://app.pulumi.com/ dashboard.

### ISSUE THREAD

**Issue by jebarpg** [pulumi/console-requests#360]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Affected area/feature

This would go on the dashboard sections under 'setting up your environment' step 2 'Select your cloud' 

Add the option for Proxmox Cloud providers in addition to [AWS, Azure, Google Cloud, Kubernetes]

I don't know what all would go into adding this additional option. But I do know that there are provider hooks for Proxmox already here
https://www.pulumi.com/ai/answers/pwHJUXDuvVAzcXaueAi6Pv/managing-proxmox-ve-vms-using-dynamic-providers
and
https://www.pulumi.com/ai/answers/k6nkDM2m11a1DDaSnFx5Bb/provisioning-proxmox-ve-vms

Thanks for taking the time to read my Feature Request.
Worm Regards

**Comment by justinvp** [comment]
Thanks for the suggestion @jebarpg. Moving this to the appropriate repo for further triage/consideration.

**Comment by caseyyh** [comment]
Hi @jebarpg thanks for bringing this to our attention!

The "setting up your environment" flow currently is a onboarding wizard built intentionally simply to capture the most major use cases as identified by our marketing team. We don't have any plans to update this flow at the current time, but I'll highlight this issue with our marketing team to see if expanding on this onboarding wizard is something to consider at a later date.

Thanks again for your suggestion!

**Comment by jebarpg** [comment]
Awesome sounds good, if there are any changes in the future I'll be interested in hearing about them. I currently am watching the releases of this GitHub repo, but keep me in mind for the future 😃. Looking forward to seeing the future developments of Pulumi. Thank you for taking the time to consider my request. 

Keep up the great work guys

Cheers 🥂
