### ISSUE TITLE
i need to delete an org 

### ISSUE THREAD

**Issue by iggym** [pulumi/console-requests#368]
### What happened?

i need to delete an org 

### Example

i need to delete an org 

### Output of `pulumi about`

i need to delete an org 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by aureq** [comment]
@iggym could you please open a support request at https://support.pulumi.com ?

Thanks

**Comment by meagancojocar** [comment]
Also, for others who might be searching for this issue, the button to delete an organization is under Organization Settings > General at the bottom of the page. 
<img width="1349" alt="Screenshot 2024-03-10 at 10 17 12 PM" src="https://github.com/pulumi/pulumi-cloud-requests/assets/50200557/3c4409c6-4e95-4cb9-99f0-398ae4a4ee24">
