### ISSUE TITLE
Transfer environments from personal account to organization

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/console-requests#370]
I have a dozen environments I need to transfer from a personal org to another org. Quite a tedious process to copy/paste the environment, open it, then copy/paste all of the individual secrets. Would be nice if this was included as a part of the new org dialog, but at a minimum if the option to "transfer environment" existed somewhere within the environments UI.

**Comment by cleverguy25** [comment]
Interesting timing, this was created around the same time https://github.com/pulumi/esc/issues/270, going to resolve this as a duplicate.
