### ISSUE TITLE
Universal dark mode

### ISSUE THREAD

**Issue by ArbiterOfBuffoonery** [pulumi/console-requests#375]
I try to use dark mode as much as possible. Looks like AI is the only part that has dark mode, everything else is light. I would love the ability to toggle to dark mode on any pulumi.com subdomain (docs, resources, app, etc)

## General Feedback

Dark mode ftw!

**Comment by aureq** [comment]
Hi @ArbiterOfBuffoonery Thanks for the feedback. 

I believe we already have a feature request about Dark mode here https://github.com/pulumi/pulumi-cloud-requests/issues/230
Please upvote and subscribe so you get updates.

Thanks
