### ISSUE TITLE
Where do I see how much money I owe you.

### ISSUE THREAD

**Issue by brentshulman-silkline** [pulumi/console-requests#380]
## General Feedback

Can't find it. pretty simple

**Comment by meagancojocar** [comment]
Hi @brentshulman-silkline, does this information not show on the Billing & Usage page for you? https://app.pulumi.com/{org-name}/settings/billing-usage

**Comment by caseyyh** [comment]
Hey @brentshulman-silkline , let us know if the above link (replacing the org name as appropriate) fixes it for you. One notable callout is that link is available only to org admins and billing admins.

I'm closing this ticket for now, but please do re-open with any follow-up if that link doesn't work or doesn't capture what you're looking for.

**Comment by brentshulman-silkline** [comment]
I had my admin role ripped from me :(    That was the problem

Any reason fro only having one admin allowed?
