### ISSUE TITLE
Resource search entry box changes while typing

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/console-requests#409]
## Expected behavior

I should be able to type a search

## Current behavior

While typing, the text I've entered disappears, then the next characters I type disappear and the original text comes back.

https://github.com/pulumi/pulumi-cloud-requests/assets/331676/8bf33173-939e-486f-a616-1d39adf455c9

## Steps to reproduce

1. Go to resource search
2. Type a long-ish word slowly.

## Context (Environment)

Was using https://app.pulumi.com/demo/resources at the time.

**Comment by tyler-dunkel** [comment]
This should be fixed now
