### ISSUE TITLE
Enable `--continue-on-error` with relevant Pulumi deployments operations

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/console-requests#411]
A user is requesting to be able to optionally turn on --continue-on-error with relevant Pulumi deployments operations (destroy/up).

## Affected feature
Pulumi Deployments

**Comment by komalali** [comment]
This is fixed by https://github.com/pulumi/pulumi/commit/cff25c2e89830d6aa42e149bf9471625d93d3dcf but yet to be released. I will close out this issue once the updated CLI is in production.

**Comment by komalali** [comment]
You can now use the `PULUMI_CONTINUE_ON_ERROR` env var to set this flag.
