### ISSUE TITLE
Deployments do not use correct package manager (PNPM)

### ISSUE THREAD

**Issue by knd775** [pulumi/console-requests#424]
While Pulumi itself can detect and use PNPM, Pulumi Cloud does not. This leads to it ignoring lockfiles, installing incorrect dependencies, and taking significantly longer (since NPM is very slow).

## General Feedback

![image](https://github.com/pulumi/pulumi-cloud-requests/assets/1235055/5643d000-e0d0-4327-b667-1498db01e7ef)

**Comment by pierskarsenbarg** [comment]
If you want to use a different package manager, in the deployment settings you should enable the `Skip automatic dependency installation step` and add any package management commands in the `Pre-run commands` bos:

<img width="759" alt="image" src="https://github.com/pulumi/pulumi-cloud-requests/assets/109047/b455cbb9-2770-4843-a420-b75f2705b4b1">

**Comment by komalali** [comment]
I think the issue here is that we don't use `pulumi install` during our dependency installation step. This has led to other issues as well, and worth tackling ASAP.

**Comment by komalali** [comment]
Looks like we got go support: https://github.com/pulumi/pulumi/issues/16781
