### ISSUE TITLE
Update REST API Docs for Org & Team Tokens

### ISSUE THREAD

**Issue by caseyyh** [pulumi/console-requests#427]
Parent Issue: https://github.com/pulumi/pulumi-cloud-requests/issues/394

## Goal

Update our REST API Docs for our org and team token API's. For new docs, we should adhere to the OpenAPI spec.

This task does not track migrating existing API's to the OpenAPI spec, but rather adding API docs where they are currently missing.

**Comment by meagancojocar** [comment]
Devon did add CRUD for team and org tokens as part of the short lived access tokens launch! leaving open as an audit item.

**Comment by djgrove** [comment]
That's correct! This has been addressed.

**Comment by djgrove** [comment]
See https://github.com/pulumi/docs/pull/12078
