### ISSUE TITLE
BUG Environment UI editor broken for several days now?

### ISSUE THREAD

**Issue by aGuyNamedJonas** [pulumi/console-requests#477]
# Bug

![Image](https://github.com/user-attachments/assets/d56d3114-8f33-4656-af0a-50c06b31e6df)
It seems like the environment editor has been broken for several days now?  

When trying to load the visual editor on https://app.pulumi.com/onstruc/esc/image-service/develop it's been showing a loading spinner of death for a few days now which is highly inconvenient. I will make due with the CLI, the visual editor has just been much faster & more reliable to use!

Sorry about probably posting this in the wrong place!

**Comment by smith558** [comment]
This should be a high priority!

**Comment by smith558** [comment]
@pierskarsenbarg @danielrbradley @aureq

**Comment by smith558** [comment]
identical to https://github.com/pulumi/pulumi-cloud-requests/issues/478

**Comment by smith558** [comment]
@aureq

**Comment by pierskarsenbarg** [comment]
Can you please try a hard refresh in your browser? This link has instructions on how to do this: https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache

**Comment by pierskarsenbarg** [comment]
If it still an issue after that please let me know

**Comment by smith558** [comment]
> Can you please try a hard refresh in your browser? This link has instructions on how to do this: https://fabricdigital.co.nz/blog/how-to-hard-refresh-your-browser-and-clear-cache

It has now resolved this. 🙂 Hard refresh for just `app.pulumi.com` didn't work, a whole browser hard refresh resolved the issue. Thank you for your swift help!

Just as a feedback, this is a bit unconvenient, as I need to reconfigure my entire browser set up now though.

**Comment by danielrbradley** [comment]
@smith558 I've noticed you've tagged me in a couple of recent service issues. I'm unable to provide any help in any of these aspects of the service product as I am part of the open source maintainers team, specifically around providers.

**Comment by pierskarsenbarg** [comment]
@aGuyNamedJonas can you please try the same as I've recommended here: https://github.com/pulumi/pulumi-cloud-requests/issues/477#issuecomment-2472895080 and see if that fixes your issue

**Comment by komalali** [comment]
If folks encounter this issue again, a hard refresh should fix it: https://github.com/pulumi/pulumi-cloud-requests/issues/477#issuecomment-2472895080

If you continue to see this, please re-open this isuse.
