### ISSUE TITLE
Regular outages not reported by status page

### ISSUE THREAD

**Issue by jkfm** [pulumi/console-requests#482]
Hi,

we regularly have the problem that in the afternoon (CET) it's not possible to open an environment to show secrets and variables. Neither the web interface nor CLI works. All requests fail with 504 errors with a hint that there may be too much traffic.

At the same time, your status page reports that all systems are operational. To me, that is really misleading since it's clearly not a one-off but sustained problem. 

When can I expect that this will be fixed?

Kind regards

**Comment by dschaller** [comment]
Hey @jkfm,

apologies about the delay here - we have been investigating the issue you've been running into and looking into the best approach to solve it.

I've done a write up in https://github.com/pulumi/esc/issues/425 which outlines why we are seeing slow opens for environments using the 1password-provider.

The reason our status page does not reflect any issues when you're unable to open environments is that this is a slightly isolated issue to only environments with either a large number of imported environments using the 1password-provider and/or environments using a lot of 1password secrets. We are actively working with the 1password team to move to a bulk API that should get rid of these latency issues and make opens work consistently for you.

I'm going to close this issue out in favor of the one mentioned above in ESC. Please follow along there for updates.
